### PR TITLE
Implement Liquibase "advanced support"

### PR DESCRIPTION
**Pull request by nvoxland**
## Description

Adds "advanced" and "contributed" test-harness tests to find what Liquibase functionality is not working against Singlestore, then addresses any failures until the tests pas

### CODE REVIEW

**Comment by nvoxland** [comment]
I created the test setup and addressed a couple failures I was able to understand:
- addLookupTable can't create a FK because singlestore doesn't support that
- add/dropForeignKey should throw a liquibase-level validation error at parse time instead of waiting for runtime

Plus copied test-harness setup/expectations from the mysql tests.

The remaining failures will take more Singlestore expertise than I have:
- Some ALTER TABLE statements give different errors depending on whether it's a rowstore or columnstore table, but are failing in both cases. Are failing change types never possible in singlestore and should be marked as not supported? Or do they sometimes work and so we can allow them, but need to set up the test scenario differently?
- Some `Cannot declare primary key or unique key named: 'PRIMARY' when using an empty shard key` type errors 
- Some datatype mapping questions
- Table remarks/comments seem to be no-ops in singlestore? Is that true? Or does the metadata need to be read from somewhere else?

**Comment by kevin-atx** [comment]
@filipelautert - the SingleStore team needs a review and feedback on their efforts to take the SingleStire extension to the Advanced verification level. Their work is in this PR. They created this document to track the work they needed to do (for your reference). https://docs.google.com/document/d/1nNAvXtTDuK0M-kqZ0gZ5spJHOyGTfCyGzqGWYqU7nj0/edit

I'm adding this to your tickets for this next sprint.

**Comment by filipelautert** [comment]
Hello @kevin-atx @oyeliseiev-ua ! I fixed some merge conflicts and started the build but we can see that some tests are not passing yet.

**Comment by oyeliseiev-ua** [comment]
> Hello @kevin-atx @oyeliseiev-ua ! I fixed some merge conflicts and started the build but we can see that some tests are not passing yet.

Hi, resolved

**Review by filipelautert — APPROVED** [review]

**Pull request merged**
